/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ProtocoloOncologico } from './types';

/**
 * Catálogo institucional de protocolos oncológicos de quimioterapia.
 *
 * Fuente: documento "Protocolos_Oncologia_Quimioterapia.xlsx" (74 esquemas).
 * El texto de cada esquema se conserva TAL CUAL viene del documento fuente:
 * son dosis teóricas y premedicaciones de uso clínico, no se reescriben.
 *
 * Este archivo se carga bajo demanda (import dinámico desde App.tsx) y solo
 * se usa la primera vez, cuando la tabla "protocolos" de Supabase está vacía:
 * en ese momento se siembra completo. A partir de ahí la fuente de verdad es
 * la base de datos y el Administrador los gestiona desde Usuarios Sistema.
 *
 * La frecuencia de aplicación se derivó del texto de ciclos del documento
 * ("cada 21 dias" -> "Cada 21 días"); cuando el documento no la precisa
 * queda como "No especificado".
 */
export type ProtocoloBase = Omit<ProtocoloOncologico, 'creado_por' | 'fecha_creacion'>;

export const PROTOCOLOS_ONCOLOGIA: ProtocoloBase[] = [
  {
    nombre: 'AC (Doxorubicina + Ciclofosfamida) en dosis densas, con esquema de neoadyuvancia, adyuvancia y taxano en dosis densas para cancer de mama (documento con multiples variantes de esquema)',
    patologia: 'Cancer de mama (neoadyuvante, adyuvante y metastasico); documento cita referencia bibliografica de doxorubicina/ciclofosfamida como quimioterapia de primera linea en cancer de mama metastasico',
    medicamentos: '- Doxorubicina (AC dosis densas): 60 mg/m2, IV en 30 minutos, dia 1 y 15\n- Ciclofosfamida (AC dosis densas): 600 mg/m2, IV en 3 horas, dia 1 y 15\n- Doxorubicina (neoadyuvancia): 60 mg/m2 (dosis total 96 mg), IV en 30 minutos, dia 1\n- Ciclofosfamida (neoadyuvancia): 600 mg/m2 (dosis total 960 mg), IV en 3 horas, dia 1\n- Paclitaxel (dosis densas taxano): 80 mg/m2 (dosis total 127 mg), IV infusion de 3 horas, dias 1, 8 y 15\n- Doxorubicina (adyuvancia): 60 mg/m2 (dosis total 96 mg), IV en 30 minutos, dia 1\n- Ciclofosfamida (adyuvancia): 600 mg/m2 (dosis total 960 mg), IV infusion de 3 horas, dia 1\n- Doxorubicina (enfermedad metastasica, ciclo 1): 60 mg/m2, IV en 30 minutos\n- Ciclofosfamida (enfermedad metastasica, ciclo 1): 600 mg/m2, IV en 3 horas\n- Doxorubicina (enfermedad metastasica, ciclo 2 si no hubo neutropenia grado 3): 60 mg/m2, IV en 30 minutos\n- Ciclofosfamida (enfermedad metastasica, ciclo 2 si no hubo neutropenia grado 3): 750 mg/m2, IV en 3 horas\n- Pegfilgrastim: 6 mg SC, dia +2 (y +16 en esquema dosis densas) (soporte, no citotoxico)',
    premedicacion: '- Fosaprepitant: 150 mg IV (No especificado (esquema AC dosis densas y neoadyuvancia))\n- Dexametasona: 16 mg IV (12 mg IV en esquema metastasico) (el dia)\n- Ondansetron: 16 mg IV (el dia)\n- Ondansetron (ambulatorio): 8 mg VO tab (cada 8 horas, No. 20)\n- Albendazol: 200 mg, 2 tab VO (al dia por 5 dias, No. 10)\n- Metronidazol: 500 mg, 1 tab VO (cada 8 h por 3 dias, No. 10)\n- Dexametasona (premedicacion taxano dosis densas): 8 mg IV (dias 1, 8 y 15)\n- Ondansetron (premedicacion taxano dosis densas): 16 mg IV (dias 1, 8 y 15)\n- Clemastina: 2 mg IV (dias 1, 8 y 15)\n- Loratadina (ambulatorio): 10 mg, 1 tab VO (iniciar 2 dias antes de quimioterapia por 4 dias, No. 12)\n- Hidratacion SSN: 1000 cc (previo a AC (adyuvancia y metastasico))\n- Ondansetron (ambulatorio metastasico): 8 mg VO (cada 8 h por 3 dias)',
    frecuencia_aplicacion: 'Cada 14 días',
    cantidad_ciclos: 'Variable segun esquema: AC dosis densas 4 ciclos cada 14 dias; taxano dosis densas 4 ciclos cada 21 dias; AC adyuvancia 4 ciclos cada 21 dias; AC enfermedad metastasica hasta 6 ciclos (o hasta 5 ciclos si se ajusta dosis) cada 21 dias',
  },
  {
    nombre: 'BEP (Bleomicina + Etoposido + Cisplatino) - dos variantes de esquema en el mismo documento',
    patologia: 'Tumor germinal testicular (esquema BEP, primera linea estandar)',
    medicamentos: '- Bleomicina (esquema 1): 30 UN IV bolo, dias 1, 8 y 15\n- Etoposido (esquema 1): 100 mg/m2 (dosis total 200 mg) IV infusion 60 min, dias 1,2,3,4,5\n- Cisplatino (esquema 1): 20 mg/m2 (dosis total 40 mg) IV infusion 60 min, dias 1,2,3,4,5\n- Pegfilgrastim (esquema 1): 6 mg SC, dia +6\n- Bleomicina (esquema 2): 30 UN IV bolo, dias 1, 8, 15, 21\n- Etoposido (esquema 2): 100 mg/m2 (dosis total 200 mg) IV infusion 60 min, dias 8,9,10,11,12\n- Cisplatino (esquema 2): 20 mg/m2 (dosis total 40 mg) IV infusion 60 min, dias 8,9,10,11,12\n- Pegfilgrastim (esquema 2): 6 mg SC, dia +13',
    premedicacion: '- SSN 0.9%: 1000 cc antes de cisplatino y 500 cc posterior (dias de aplicacion de cisplatino)\n- Ondansetron: 16 mg IV (esquema 1) / 15 mg IV (bleomicina esquema 2) (dias 1 al 5 (esquema 1) / dias 8-12 (esquema 2))\n- Fosaprepitant: 150 mg IV (dia 1 (esquema 1) / dia 8 (esquema 2))\n- Dexametasona: 8 mg IV (dias 1 al 5 (esquema 1) / dias 8-12 (esquema 2))\n- Furosemida: 20 mg IV (al terminar SSN)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 dias (cantidad total no especificada)',
  },
  {
    nombre: 'Bevacizumab + Atezolizumab',
    patologia: 'No especificado (combinación biológica/inmunoterapia IV, sin diagnóstico explícito en el documento)',
    medicamentos: '- Bevacizumab: 15 mg/kg IV día 1 (infusión de 90 min)\n- Atezolizumab: 1200 mg IV día 1 (infusión de 60 min)',
    premedicacion: '- Difenhidramina: 50 mg IV (No especificado)\n- Acetaminofén: 1 gr VO (No especificado)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 días (número total no especificado)',
  },
  {
    nombre: 'Bevacizumab + Doxorrubicina liposomal + Carboplatino',
    patologia: 'Cáncer de ovario (BRCA 1/2, seguimiento con CA 125)',
    medicamentos: '- Bevacizumab: 7.5 mg/kg (dosis total 675 mg) IV días 1 y 15 (infusión de 1 hora)\n- Doxorrubicina liposomal: 30-40 mg/m2 (dosis total 43 mg) IV día 1 (infusión de 1 hora)\n- Carboplatino: AUC 5 (dosis total 420 mg) IV Día 1 (infusión de 1 hora)',
    premedicacion: '- Pegfilgrastim: 6 mg SCT (día +2)\n- Ondansetron: 16 mg IV (día 1)\n- Dexametasona: 16 mg IV (día 1 y 15)\n- Fosaprepitant: 150 mg IV (día 1)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'Ciclos cada 28 días (número total no especificado)',
  },
  {
    nombre: 'Bevacizumab - Paclitaxel - Carboplatino',
    patologia: 'No especificado en el documento (se solicita CA 125 y TAC de tórax/abdomen/pelvis en seguimiento, sugestivo de cáncer de ovario; el esquema Bevacizumab-Paclitaxel-Carboplatino es estándar en cáncer de ovario epitelial avanzado)',
    medicamentos: '- Bevacizumab: 15 mg/kg (Dosis total 900 mg IV, infusión de 1 hora, día 1)\n- Paclitaxel: 175 mg/m2 (Dosis total 276 mg IV, infusión de 3 horas, día 1)\n- Carboplatino: AUC 5 (Dosis total 625 mg IV, infusión de 1 hora, día 1)\n- Pegfilgrastim: 6 mg SCT, día +2',
    premedicacion: '- Hidratación SSN: 1000 cc (previa)\n- Ondansetron: 16 mg IV (No especificado)\n- Dexametasona: 8 mg IV (No especificado)\n- Clemastina: 2 mg IV (No especificado)\n- Ondansetron (ambulatorio): tab 8 mg, 1 tab VO (cada 8 horas, No 20)\n- Loratadina: tab 10 mg, 1 tab noche (iniciar 2 días antes del ciclo, No 5)\n- Prednisolona: tab 5 mg, 2 tab (cada 12 h por 2 días, iniciar un día antes del paclitaxel, No 16)\n- Albendazol: tab 200 mg, 2 tab VO (por 5 días)\n- Metronidazol: tab 500 mg, 1 tab VO (cada 8 horas por 3 días)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '6 ciclos, cada 21 días',
  },
  {
    nombre: 'Bleomicina + Etoposido + Carboplatino (esquema tipo BEP, ajustado para dialisis)',
    patologia: 'Tumor de celulas germinales (probable testicular), seguimiento con BHCG y AFP',
    medicamentos: '- Bleomicina: 30 UI IV bolo, dia 2\n- Etoposido: 50 mg/m2 IV infusion 60 min, dias 1 al 5 (ajustado a 50% de la dosis por dialisis)\n- Carboplatino: AUC 5 IV infusion 1 hora, dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1 al 5)\n- Fosaprepitant: 150 mg IV (dia 1)\n- Dexametasona: 8 mg IV (dia 1 al 5)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '4 ciclos (ciclos cada 21 dias)',
  },
  {
    nombre: 'Bleomicina + Etopósido + Cisplatino (BEP, adaptado a paciente en hemodiálisis)',
    patologia: 'Tumor de células germinales (probable origen testicular, seguimiento con AFP y BHCG cuantitativa)',
    medicamentos: '- Bleomicina: 12 Un IV bolo días 1, 8 y 15 (40% de la dosis total en paciente en diálisis)\n- Etopósido: 50 mg/m2 (dosis total 155 mg) IV días 1 al 5 (infusión de 60 min) (50% de la dosis, sin relación temporal con hemodiálisis)\n- Cisplatino: 10 mg/m2 (dosis total 31 mg) IV días 1, 3 y 5 (infusión de 60 min) (50% de la dosis administrada post diálisis)',
    premedicacion: '- Ondansetron: 16 mg IV (días 1 al 5)\n- Metoclopramida: 10 mg IV (días 1 al 5)\n- Fosaprepitant: 150 mg IV (día 1)\n- Dexametasona: 8 mg IV (días 1 al 5)\n- Dexametasona (premedicación bleomicina): 8 mg IV (día)\n- Ondansetron (premedicación bleomicina): 16 mg IV (día)\n- Pegfilgrastim: 6 mg SCT (día 6)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 días (1 ciclo formulado; total de ciclos no especificado)',
  },
  {
    nombre: 'Cabazitaxel',
    patologia: 'Cancer de prostata metastasico resistente a castracion (uso de cabazitaxel + denosumab + prednisolona, esquema tipico de esta indicacion)',
    medicamentos: '- Cabazitaxel: 20 mg/m2 IV infusion de 60 minutos',
    premedicacion: '- Dexametasona: 16 mg IV (No especificado)\n- Difenhidramina: 25 mg IV (No especificado)\n- Ondansetron: 16 mg IV (No especificado)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo formulado; ciclos cada 21 dias',
  },
  {
    nombre: 'Capecitabina - Mitomicina (ciclo impar) / Capecitabina monoagente (ciclo par)',
    patologia: 'No especificado en el documento (se solicita CA 19-9 en seguimiento, sugestivo de neoplasia gastrointestinal/pancreatobiliar; combinación Mitomicina-Capecitabina usada en cáncer gástrico o colorrectal)',
    medicamentos: '- Mitomicina: 7 mg/m2 (no exceder 20 mg dosis total), IV día 1, cada 43 días\n- Capecitabina: 2000 mg/m2, dosis total 3000 mg, tomar 3 tab (500 mg) 7am y 3 tab 7pm por 14 días',
    premedicacion: '- Dexametasona: 16 mg IV (día 1)\n- Ondansetron: 16 mg IV (día 1)\n- Ondansetron (ambulatorio): tab 8 mg, 1 tab (cada 12 horas x 10 días)',
    frecuencia_aplicacion: 'Cada 43 días',
    cantidad_ciclos: 'Ciclo impar con Mitomicina+Capecitabina cada 43 días; ciclo par con Capecitabina monoagente',
  },
  {
    nombre: 'Capecitabine + Bevacizumab',
    patologia: 'No especificado',
    medicamentos: '- Capecitabine: 1000 mg/m2 VO cada 12 horas, dias 1-14 (dosis total 2500)\n- Bevacizumab: 500 mg (7.5 mg/kg) IV en infusion de 90 min, dia 1',
    premedicacion: '- Dexametasona: 4 mg IV (No especificado)\n- Ranitidina: 50 mg IV (No especificado)\n- Loperamida (formula casa): 2 mg tab, 1 tab VO (cada 6 horas en caso de diarrea, No 20)\n- Ondansetron (formula casa): 8 mg tab, 1 tab VO (cada 12 horas, No 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 dias',
  },
  {
    nombre: 'CAPEOX + Bevacizumab metastasico',
    patologia: 'Cancer colorrectal (metastasico)',
    medicamentos: '- Capecitabina: 1000 mg/m2 VO cada 12h, dias 1-14\n- Oxaliplatino: 130 mg/m2 IV infusion 3 horas, dia 1\n- Bevacizumab: 7.5 mg/kg IV infusion 90 min, dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'No especificado (ciclos cada 21 dias)',
  },
  {
    nombre: 'CAPEOX adyuvante + Bevacizumab',
    patologia: 'Cancer colorrectal (adyuvante)',
    medicamentos: '- Capecitabina: 1000 mg/m2 VO cada 12h, dias 1-14\n- Oxaliplatino: 130 mg/m2 IV infusion 3 horas, dia 1\n- Bevacizumab: 7.5 mg/kg IV infusion 90 min, dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '8 ciclos, cada 21 dias',
  },
  {
    nombre: 'CAPEOX metastasico',
    patologia: 'Cancer colorrectal (metastasico)',
    medicamentos: '- Capecitabina: 1000 mg/m2 VO cada 12h, dias 1-14\n- Oxaliplatino: 130 mg/m2 IV infusion 3 horas, dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'No especificado (ciclos cada 21 dias)',
  },
  {
    nombre: 'CAPIRI metastasico',
    patologia: 'Cancer colorrectal (metastasico)',
    medicamentos: '- Capecitabina: 1000 mg/m2 VO cada 12h, dias 1-14\n- Irinotecan: 180 mg/m2 IV infusion 1 hora, dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1)\n- Atropina: 0.5 mg SCT (30 min antes de irinotecan)\n- Ranitidina: 50 mg IV (dia 1)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'No especificado (ciclos cada 21 dias)',
  },
  {
    nombre: 'Carboplatino + Etoposido',
    patologia: 'Cancer de pulmon de celulas pequenas (esquema Carboplatino + Etoposido, estandar en carcinoma pulmonar microcitico, alternativa a EP con cisplatino en pacientes con funcion renal reducida)',
    medicamentos: '- Carboplatino: AUC 5 (dosis total 273 mg), dia 1\n- Etoposido: 100 mg/m2 (dosis total 172 mg), infusion de 3 horas, dias 1 al 3\n- Pegfilgrastim: 6 mg SC, dia +4 (soporte, no citotoxico)',
    premedicacion: '- SSN 0.9%: 1000 cc (en bolo)\n- Fosaprepitant: 150 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1-2-3)\n- Ondansetron: 16 mg IV (dia 1-2-3)\n- Ondansetron (ambulatorio): 8 mg VO tab (cada 12 horas, No. 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo, ciclos cada 21 dias (No especificado el numero total)',
  },
  {
    nombre: 'Carboplatino + Paclitaxel',
    patologia: 'No especificado (probable cancer ginecologico; se solicita CA 125 de control)',
    medicamentos: '- Paclitaxel: 60 mg/m2 (dosis total 94 mg) IV infusion 3 horas, dias 1, 8 y 15\n- Carboplatino: AUC 2 (dosis total 72 mg) IV infusion 30 minutos, dias 1, 8 y 15',
    premedicacion: '- Dexametasona: 16 mg IV (dia 1)\n- Difenhidramina: 50 mg VO (120 minutos antes de cada aplicacion de paclitaxel)\n- Ondansetron: 16 mg IV (No especificado (dia de aplicacion))\n- Fosaprepitant: 150 mg IV (dia 1)\n- Ondansetron (VO ambulatorio): 8 mg (1 tab VO) (cada 8 horas)\n- Prednisolona: 5 mg (2 tab) (cada 12 horas por 2 dias, iniciar un dia antes del paclitaxel)\n- Albendazol: 200 mg (2 tab VO) (por 5 dias)\n- Metronidazol: 500 mg (1 tab VO) (cada 8 horas por 3 dias)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 21 dias (cantidad total no especificada)',
  },
  {
    nombre: 'Carboplatino + Paclitaxel + Atezolizumab + Bevacizumab',
    patologia: 'Cáncer de pulmón no microcítico (no escamoso), metastásico',
    medicamentos: '- Bevacizumab: 15 mg/kg IV día 1 (infusión de 90 min)\n- Atezolizumab: 1200 mg IV día 1 (infusión de 60 min)\n- Paclitaxel: 200 mg/m2 (dosis total 360 mg) IV día 1 (infusión de 3 horas)\n- Carboplatino: AUC 5-6 (dosis total 480 mg) IV día 1 (infusión de 30 min)',
    premedicacion: '- Pegfilgrastim: 6 mg SCT (día 2)\n- Fosaprepitant: 150 mg IV (día 1)\n- Ondansetron: 16 mg IV (día 1)\n- Dexametasona: 4 mg IV (día 1)\n- Difenhidramina: 50 mg IV (antes de paclitaxel)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 días (número total de ciclos no especificado)',
  },
  {
    nombre: 'Carboplatino + Paclitaxel + Pembrolizumab (con segundo esquema Paclitaxel + Carboplatino en el mismo documento)',
    patologia: 'No especificado (esquema compatible con cancer de pulmon/ginecologico tratado con platino-taxano-pembrolizumab; diagnostico no explicitado en el documento)',
    medicamentos: '- Paclitaxel: 175 mg/m2 (dosis total 315 mg) IV infusion 3 horas, dia 1\n- Carboplatino: AUC 5-6 (dosis total 597 mg) IV infusion 1 hora, dia 1\n- Pembrolizumab: 200 mg IV infusion 60 min, dia 1\n- Pegfilgrastim: 6 mg SC, dia +2\n- Paclitaxel (esquema 2, mismo documento): 80 mg/m2 (dosis total 116 mg) IV infusion 3 horas, dias 1, 8 y 15\n- Carboplatino (esquema 2, mismo documento): AUC 6 (dosis total 600 mg) IV infusion 1 hora, dia 1',
    premedicacion: '- SSN (hidratacion): 1000 cc (previa a quimioterapia)\n- Ondansetron: 16 mg IV (No especificado)\n- Dexametasona: 4 mg IV (esquema 1) / 8 mg IV (esquema 2) (No especificado)\n- Difenhidramina: 50 mg IV (No especificado)\n- Ranitidina (esquema 2): 50 mg IV (No especificado)\n- Ondansetron (VO ambulatorio): 8 mg (1 tab VO) (cada 8 horas)\n- Loratadina: 10 mg (1 tab VO) (noche, iniciar 2 dias antes de quimioterapia por 3-5 dias)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 21 dias (cantidad total no especificada)',
  },
  {
    nombre: 'Carboplatino + Pemetrexed',
    patologia: 'Cancer de pulmon no microcitico (adenocarcinoma pulmonar) - esquema estandar Carboplatino + Pemetrexed en primera linea de NSCLC no escamoso',
    medicamentos: '- Pemetrexed: 500 mg/m2 (dosis total 725 mg), IV infusion de 10 minutos, dia 1\n- Carboplatino: AUC 5 (dosis total 350 mg), infusion de 30 minutos posterior a administrar pemetrexed, dia 1',
    premedicacion: '- Acido folico: 1 mg VO (al dia por 30 dias (ya administrado))\n- Vitamina B12: 1000 mcg (dia 1 (ya administrado))\n- Cianocobalamina: 1 ampolla IM (No especificado)\n- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (No especificado)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo, ciclos cada 21 dias (No especificado el numero total)',
  },
  {
    nombre: 'Carboplatino + Pemetrexed + Pembrolizumab',
    patologia: 'Cancer de pulmon no microcitico no escamoso (esquema estandar carboplatino-pemetrexed-pembrolizumab; se solicita EGFR en biopsia liquida)',
    medicamentos: '- Pemetrexed: 500 mg/m2 (dosis total 875 mg) IV infusion 10 minutos, dia 1\n- Carboplatino: AUC 5-6 (dosis total 500 mg) IV infusion 30 minutos, dia 1\n- Pembrolizumab: 200 mg IV infusion 30 minutos, dia 1\n- Pegfilgrastim: 6 mg SC, dia 2',
    premedicacion: '- Difenhidramina: 50 mg IV (dia 1)\n- Ondansetron: 16 mg IV (dia 1)\n- Fosaprepitant: 150 mg IV (dia 1)\n- Ondansetron (VO ambulatorio): 8 mg (1 tab VO) (cada 12 horas)\n- Albendazol: 200 mg (2 tab VO) (por 5 dias)\n- Acido folico: 1 mg VO (diario, iniciar 7 dias antes del ciclo 1 y continuar hasta dia 21 posterior a terminar pemetrexed)\n- Vitamina B12: 1000 mcg (cada 9 semanas, iniciar 7 dias antes del ciclo 1 y continuar hasta dia 21 posterior a terminar pemetrexed)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 21 dias (cantidad total no especificada)',
  },
  {
    nombre: 'Carboplatino, Paclitaxel, Atezolizumab y Bevacizumab',
    patologia: 'No especificado',
    medicamentos: '- Carboplatino: AUC=6\n- Paclitaxel: 175 mg/m2\n- Atezolizumab: dosis fija 1200 mg IV\n- Bevacizumab: 15 mg/kg',
    premedicacion: '- Dexametasona: 16 mg IV (antes de la quimioterapia, dia 1 del ciclo)\n- Ondansetron: 16 mg IV (antes de la quimioterapia, dia 1 del ciclo)\n- Clemastina: 2 mg IV (dia 1)\n- Pegfilgrastim: 6 mg jeringa prellenada (No especificado (dia 2 del ciclo, subcutaneo segun texto adicional))\n- Loratadina (para casa): 10 mg, 2 tabletas (1 hora antes de la quimioterapia, luego 1 tableta cada 12 horas)\n- Ondansetron (para casa): 8 mg tableta (1 tableta cada 12 horas si presenta nauseas y/o vomito)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1er a 4to-6to ciclo, cada 21 dias',
  },
  {
    nombre: 'CF + Cetuximab (Cisplatino + 5-Fluorouracilo + Cetuximab)',
    patologia: 'Cancer de cabeza y cuello (escamocelular), esquema CF+Cetuximab (protocolo tipo EXTREME); documento no consigna sitio anatomico exacto',
    medicamentos: '- Cetuximab (ciclo 1, dosis de carga): 400 mg/m2 IV infusion 2 horas, dia 1\n- Cetuximab (mantenimiento): 250 mg/m2 IV infusion 2 horas, dia 8 y 15 (y semanas posteriores)\n- Cisplatino: 100 mg/m2 IV infusion 1 hora, dia 1\n- 5-Fluorouracilo: 1000 mg/m2 IV infusion en 24 horas, dias 1 al 4',
    premedicacion: '- SSN 0.9%: 1000 cc en bolo (No especificado)\n- Fosaprepitant: 150 mg IV (dia 1 (ciclo 1); dia 1 (ciclo 2))\n- Dexametasona: 16 mg IV (ciclo 1) / 8 mg IV (ciclo 2) (dia 1 al 4 (ciclo 1); dia 1 (ciclo 2))\n- Ondansetron: 16 mg IV (dia 1 al 4 (ciclo 1); dia 1 (ciclo 2))\n- Furosemida: 20 mg IV (al terminar cisplatino)\n- Difenhidramina (premedicacion cetuximab): 50 mg VO (No especificado)\n- Clemastina (premedicacion cetuximab): 2 mg IV (No especificado)\n- Manitol al 20% (ciclo 2): 50 cc bolo, seguido de 25 cc/hora concurrente con cisplatino (antes de cisplatino)\n- Ranitidina (ciclo 2): 50 mg IV (No especificado)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'No especificado (ciclos cada 21 dias)',
  },
  {
    nombre: 'Cisplatino + Doxorubicina (neoadyuvante)',
    patologia: 'Sarcoma oseo (osteosarcoma) - esquema neoadyuvante; documento incluye interconsulta a ortopedia oncologica, consistente con tumor oseo primario',
    medicamentos: '- Cisplatino: 100 mg/m2 (dosis total 160 mg), IV infusion de 4 horas, dia 1\n- Doxorubicina: 25 mg/m2/dia (dosis total 40 mg), IV infusion de 1 hora, dias 1, 2 y 3\n- Pegfilgrastim: 6 mg SC, dia +4 (soporte, no citotoxico)',
    premedicacion: '- SSN 0.9%: 1000 cc (antes y despues de cisplatino)\n- Fosaprepitant: 150 mg IV (dia 1)\n- Ondansetron: 16 mg IV (dias 1 al 3)\n- Dexametasona: 16 mg IV (dias 1 al 3)\n- Furosemida: 20 mg IV (el dia, despues de terminar SSN 0.9%)\n- Albendazol: 200 mg, 2 tab VO (al dia por 5 dias, No. 10)\n- Metronidazol: 500 mg, 1 tab VO (cada 8 h por 3 dias, No. 10)\n- Ondansetron (ambulatorio): 8 mg VO tab (cada 12 horas, No. 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '4 ciclos, cada 21 dias (neoadyuvante)',
  },
  {
    nombre: 'Cisplatino + Etoposido',
    patologia: 'Cancer de pulmon de celulas pequenas (esquema EP - Cisplatino + Etoposido, estandar en carcinoma pulmonar microcitico); documento incluye interconsulta a cirugia hepatobiliar',
    medicamentos: '- Cisplatino: 25 mg/m2 (dosis total 39 mg), IV infusion de 3 horas, dias 1 al 3\n- Etoposido: 100 mg/m2 (dosis total 157 mg), infusion de 3 horas, dias 1 al 3\n- Pegfilgrastim: 6 mg SC, dia 4 (soporte, no citotoxico)',
    premedicacion: '- SSN 0.9%: 1000 cc (en bolo)\n- Fosaprepitant: 150 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1-2-3)\n- Ondansetron: 16 mg IV (dia 1-2-3)\n- Furosemida: 20 mg IV (previo a cisplatino)\n- SSN 0.9% + cloruro de potasio: 500 cc + 5 cc de cloruro de potasio (a 60 cc/hora)\n- Ondansetron (ambulatorio): 8 mg VO tab (cada 12 horas, No. 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo, ciclos cada 21 dias (No especificado el numero total)',
  },
  {
    nombre: 'CVD Paraganglioma (Ciclofosfamida - Vincristina - Dacarbazina)',
    patologia: 'Paraganglioma (esquema CVD, indicado explícitamente en el encabezado del documento: \'CVD PARAGANGLIOMA\')',
    medicamentos: '- Ciclofosfamida: 750 mg/m2 IV, dosis total No especificado (valor ilegible en PDF), día 1\n- Vincristina: 1.4 mg/m2 IV, dosis total No especificado (valor ilegible en PDF), no superar los 2 mg, día 1\n- Dacarbazina: 600 mg/m2 IV, dosis total No especificado (valor ilegible en PDF), días 1 y 2',
    premedicacion: '- Dexametasona: 16 mg IV (previo a quimioterapia, días 1 y 2)\n- Ondansetron: 16 mg IV (previo a quimioterapia, días 1 y 2)\n- Ondansetron (ambulatorio): 8 mg VO (cada 12 horas en caso de náuseas y/o vómito)\n- Pegfilgrastim: 6 mg SC (día 2)',
    frecuencia_aplicacion: 'No especificado',
    cantidad_ciclos: 'No especificado (documento muestra ciclo 1)',
  },
  {
    nombre: 'Dacarbazina monoterapia',
    patologia: 'Melanoma metastasico o sarcoma de tejidos blandos (dacarbazina monoterapia es esquema estandar en estas indicaciones); No especificado explicitamente en el documento',
    medicamentos: '- Dacarbazina: 1200 mg/m2 (dosis total 1824 mg), IV infusion de 30 minutos, dia 1\n- Gluconato de calcio 10%: 5 ml antes, durante y posterior al inicio de dacarbazina (protector, no citotoxico)',
    premedicacion: '- Ondansetron: 16 mg IV (el dia)\n- Dexametasona: 16 mg IV (el dia)\n- Ondansetron (ambulatorio): 8 mg VO tab (cada 12 horas, No. 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo, ciclos cada 21 dias (No especificado el numero total)',
  },
  {
    nombre: 'Docetaxel monoterapia',
    patologia: 'No especificado en el documento (control de PSA en seguimiento sugiere cáncer de próstata; Docetaxel monoterapia también se usa en cáncer de mama o pulmón)',
    medicamentos: '- Docetaxel: 75 mg/m2 (Dosis total 140 mg IV, infusión de 1 hora, día 1)',
    premedicacion: '- Dexametasona: 16 mg IV (No especificado)\n- Ondansetron: 16 mg IV (No especificado)\n- Loratadina: 10 mg tab, 1 cada noche (iniciar 3 días antes de quimioterapia)\n- Ondansetron (ambulatorio): tab 8 mg, 1 tab VO (cada 8 horas x 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 días',
  },
  {
    nombre: 'Docetaxel semanal',
    patologia: 'No especificado (documento no consigna diagnostico explicito; consentimiento generico de quimioterapia citotoxica)',
    medicamentos: '- Docetaxel: 40 mg/m2 IV infusion 1 hora, dias 1, 8 y 15',
    premedicacion: '- Dexametasona: 16 mg IV (No especificado)\n- Ranitidina: 50 mg IV (No especificado)\n- Ondansetron: 16 mg IV (No especificado)\n- Loratadina: 10 mg VO (1 cada noche, iniciar 3 dias antes de quimioterapia)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'No especificado (ciclos cada 21 dias)',
  },
  {
    nombre: 'Doxorrubicina - Ciclofosfamida (adyuvante)',
    patologia: 'No especificado en el documento (esquema Doxorrubicina-Ciclofosfamida (AC) es estándar en cáncer de mama adyuvante)',
    medicamentos: '- Doxorrubicina: 60 mg/m2, dosis total 108 mg IV\n- Ciclofosfamida: 600 mg/m2, dosis total 1080 mg IV\n- Pegfilgrastim: 6 mg SCT on body inyector, día +1',
    premedicacion: '- Dexametasona: 16 mg IV (día 1)\n- Ondansetron: 16 mg IV (día 1)\n- Loperamida: tab 2 mg, 1 tab VO (cada 8 horas en caso de diarrea, No 20)\n- Ondansetron (ambulatorio): tab 8 mg, 1 tab VO (cada 8 horas por 5 días, en caso de náuseas o vómito, No 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 días (documento describe ciclo 1/4)',
  },
  {
    nombre: 'Doxorrubicina liposomal + Bevacizumab',
    patologia: 'No especificado explicitamente en el documento (esquema compatible con cancer de ovario recurrente)',
    medicamentos: '- Doxorrubicina liposomal: 40 mg/m2 (dosis total 68 mg) IV en infusion de 1 hora, dia 1\n- Bevacizumab: 7.5 mg/kg (dosis total 525 mg) IV en infusion de 90 minutos, dia 1 y 15',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1)\n- Difenhidramina tab: 50 mg VO (dia 15 (dia de quimioterapia))',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 28 dias (No especificado el numero total de ciclos del esquema)',
  },
  {
    nombre: 'Doxorrubicina liposomal + Carboplatino',
    patologia: 'No especificado (cancer ginecologico/oncologico no precisado en el documento; se solicita CA 125 y CEA de control)',
    medicamentos: '- Carboplatino: AUC 5 (dosis total 675 mg) IV, infusion de 30 minutos, Dia 1\n- Doxorrubicina liposomal: 30 mg/m2 (dosis total 45 mg) IV, infusion 30 minutos, Dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (Dia 1)\n- Dexametasona: 16 mg IV (Dia 1)\n- Loperamida: 2 mg (1 tab VO) (cada 8 horas en caso de diarrea (ambulatorio))\n- Ondansetron (VO ambulatorio): 8 mg (1 tab VO) (cada 8 horas por 5 dias)\n- Acetaminofen: 500 mg (2 tab VO) (cada 8 horas)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 28 dias (cantidad total no especificada)',
  },
  {
    nombre: 'Doxorrubicina liposomal monoterapia (20 mg/m2)',
    patologia: 'No especificado (esquema compatible con cancer de mama metastasico o sarcoma; sin diagnostico explicito en el documento)',
    medicamentos: '- Doxorrubicina liposomal: 20 mg/m2 (dosis total 34 mg) IV en infusion de 1 hora, dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1, previo a quimioterapia)\n- Clemastina: 2 mg (dia 1, previo a quimioterapia)\n- Ondansetron tab 8 mg (ambulatorio): 1 tab VO (cada 8 horas, No 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 21 dias (No especificado el numero total de ciclos del esquema)',
  },
  {
    nombre: 'Doxorrubicina liposomal monoterapia (30 mg/m2)',
    patologia: 'No especificado (esquema compatible con cancer de mama metastasico, sarcoma o cancer de ovario; sin diagnostico explicito en el documento)',
    medicamentos: '- Doxorrubicina liposomal: 30 mg/m2 (dosis total 42 mg) IV en infusion de 1 hora, dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (No especificado)\n- Dexametasona: 16 mg IV (No especificado)\n- Fosaprepitant: 150 mg IV (dia)\n- Ondansetron tab 8 mg (ambulatorio): 1 tab VO (cada 8 horas, No 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 21 dias (No especificado el numero total de ciclos del esquema)',
  },
  {
    nombre: 'EMA-CO (con variantes: EMACO dosis altas de metotrexate para compromiso SNC, EMA-EP para puntuacion de riesgo mayor a 12)',
    patologia: 'Neoplasia trofoblastica gestacional (coriocarcinoma) - seguimiento con hCG',
    medicamentos: '- Etoposido: 100 mg/m2 IV durante 30 minutos, dias 1 y 2\n- Metotrexato: 100 mg/m2 IV bolo, seguido de 200 mg/m2 IV en infusion de 12 horas, dia 1\n- Dactinomicina D: 0.5 mg IV bolo, dias 1 y 2\n- Ciclofosfamida: 600 mg/m2 IV, dia 8\n- Vincristina: 1.0 mg/m2 IV, dia 8\n- Etoposido (variante SNC): 100 mg/m2 IV durante 60 minutos, dias 1 y 2\n- Metotrexato (variante SNC): 1000 mg/m2 IV durante 24 horas, dia 1\n- Cisplatino (variante EMA-EP): 60 mg/m2 IV, dia 8',
    premedicacion: '- Ondansetron: 16 mg (No especificado (previo a esquema))\n- Dexametasona: 16 mg (No especificado (previo a esquema))\n- Folinato de calcio (rescate, no premedicacion antiemetica): 30 mg IV (cada 12 h por 4 dosis, comenzando 24 horas despues del inicio de MTX)',
    frecuencia_aplicacion: 'Cada 15 días',
    cantidad_ciclos: 'Ciclos cada 15 dias; continuar hasta hCG indetectable durante 3 semanas consecutivas, mas al menos 3 cursos adicionales de consolidacion',
  },
  {
    nombre: 'Esquema CLEOPATRA (Pertuzumab + Trastuzumab + Docetaxel), con variante que incluye Carboplatino',
    patologia: 'Cancer de mama HER2 positivo metastasico (esquema CLEOPATRA: Pertuzumab + Trastuzumab + Docetaxel, estandar en primera linea de cancer de mama metastasico HER2+)',
    medicamentos: '- Pertuzumab: dosis 840 mg, dia 1 (1 ampolla)\n- Trastuzumab (dosis de carga): 8 mg/kg, dosis de carga, aplicar 656 mg IV dia 1 (variante 2: 400 mg IV)\n- Docetaxel: 75 mg/m2, dosis total 145 mg (variante 2: dosis total 107 mg), IV infusion de 3 horas, dia 1\n- Carboplatino (variante 2): AUC 5, TFG 47 ml/min, dosis 361 mg IV, cada 21 dias',
    premedicacion: '- Dexametasona: 16 mg IV (premedicacion de docetaxel)\n- Medicamento no especificado (dosis \'2 mg IV\'): 2 mg IV (dia 1 (No especificado el nombre del medicamento en el texto extraido))\n- Ondansetron: 16 mg IV (premedicacion de docetaxel)\n- Pegfilgrastim (variante 2): 6 mg SC (dia 2)\n- Loratadina (ambulatorio): 10 mg VO tab (1 tab al dia por 5 dias, iniciar 2 dias antes de quimioterapia)\n- Ondansetron (ambulatorio): 8 mg VO tab (cada 12 horas, No. 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclo 1 con dosis de carga, cada 21 dias (proximo ciclo reduce dosis de pertuzumab y trastuzumab); No especificado el numero total de ciclos',
  },
  {
    nombre: 'Esquema CROSS (Paclitaxel + Carboplatino concurrente con radioterapia)',
    patologia: 'Cáncer de esófago (esquema CROSS neoadyuvante con radioterapia 41.4 Gy)',
    medicamentos: '- Paclitaxel: 50 mg/m2 (dosis total 67 mg) infusión de 3 horas, días 1-8-15\n- Carboplatino: AUC 2 (dosis total 234 mg) infusión de 1 hora, días 1-8-15',
    premedicacion: '- Ondansetron: 16 mg IV (día de quimioterapia)\n- Dexametasona: 8 mg IV (día de quimioterapia)\n- Difenhidramina: 50 mg VO (el día de quimioterapia)',
    frecuencia_aplicacion: 'Semanal',
    cantidad_ciclos: 'Aplicación semanal por 5 semanas (esquema CROSS, días 1-8-15)',
  },
  {
    nombre: 'ESQUEMA GEMCITABINA - CISPLATINO',
    patologia: 'No especificado (esquema Gemcitabina-Cisplatino; nota del documento referencia dosis alternativa para cáncer de vejiga y vesícula biliar, sugiriendo indicación en tracto urinario o vía biliar; diagnóstico no explícito)',
    medicamentos: '- Gemcitabina: 1000 mg/m2 (Dosis total 1620 mg) IV en infusión de 60 minutos, día 1 y 8\n- Cisplatino: 25 mg/m2, día 1 y 8 (Nota: si se prescribe cisplatino SOLO día 1, la dosis es 70 mg/m2 para vejiga y vesícula biliar)\n- Pegfilgrastim: 6 mg SC, día 1 (soporte, no citotóxico)',
    premedicacion: '- SSN 0.9%: 1000 cc IV en bolo (día 1 y 8)\n- Dexametasona: 16 mg IV (día 1-8-15)\n- Ondansetron: 16 mg IV (día 1-8-15)\n- Furosemida: 20 mg IV (previo a cisplatino)\n- SSN 0.9% + Cloruro de potasio: 500 cc + 5 cc de cloruro de potasio a 60 cc/hora (No especificado)\n- Ondansetron (ambulatorio): 8 mg tab VO (1 tab cada 12 horas, No 30)',
    frecuencia_aplicacion: 'Cada 4 semanas',
    cantidad_ciclos: 'No especificado (se formula primer ciclo, ciclos cada 4 semanas)',
  },
  {
    nombre: 'ESQUEMA GEMCITABINA-CAPECITABINA DIA 1-8-15',
    patologia: 'No especificado (probable cancer de vias biliares/vesicula biliar por nota de dosis de cisplatino para vejiga y vesicula biliar)',
    medicamentos: '- Gemcitabina: 1000 mg/m2 (dosis total 1620 mg) IV en infusion de 60 minutos, dia 1, 8 y 15\n- Capecitabina: 1660 mg/m2/dia, dia 1 al dia 21, tomar 3 tabletas AM y 2 tabletas PM por 21 dias',
    premedicacion: '- SSN 0.9%: 1000 cc en bolo (dia 1 y 8)\n- Dexametasona: 16 mg IV (dia 1-8-15)\n- Ondansetron: 16 mg IV (dia 1-8-15)\n- Furosemida: 20 mg IV (previo a cisplatino)\n- SSN 0.9% + cloruro de potasio: 500 CC + 5 CC de cloruro de potasio a 60 cc hora (No especificado)\n- Pegfilgrastim: 6 mg subcutaneo (dia 1 y dia 15)\n- Ondansetron (formula casa): 8 mg VO (cada 12 horas por 30 tabletas)',
    frecuencia_aplicacion: 'Cada 4 semanas',
    cantidad_ciclos: 'No especificado (se formula primer ciclo, ciclos cada 4 semanas)',
  },
  {
    nombre: 'Esquema NIGRO',
    patologia: 'No especificado en el documento (el esquema NIGRO con Mitomicina + Fluorouracilo es el tratamiento estándar de carcinoma escamocelular de canal anal)',
    medicamentos: '- Mitomicina: 12 mg/m2 (dosis máxima 20 mg), dosis total 15 mg, día 1\n- Fluorouracilo: equivalente a 1000 mg/m2/día, infusión continua de 4 días (día 1 al 4 y día 29 al 32)',
    premedicacion: '- Ondansetron: 16 mg (día 1 y 29)\n- Dexametasona: 16 mg (día 1 y 29)\n- Ondansetron (ambulatorio): tab 8 mg, 1 tab (cada 12 horas x 20 días)',
    frecuencia_aplicacion: 'No especificado',
    cantidad_ciclos: 'Esquema en día 1 y día 29 (2 aplicaciones, se prescribe día 1)',
  },
  {
    nombre: 'Esquema TIP (Paclitaxel + Ifosfamida + Cisplatino)',
    patologia: 'Tumor de celulas germinales o sarcoma de tejidos blandos (esquema TIP de rescate, uso tipico en tumores germinales refractarios y sarcomas); No especificado explicitamente en el documento',
    medicamentos: '- Paclitaxel: 175 mg/m2 (dosis total 306 mg), IV infusion de 3 horas, dia 1\n- Ifosfamida: 1200 mg/m2 (dosis total 2100 mg), IV infusion de 2 horas, dias 1, 2 y 3\n- Cisplatino: 25 mg/m2 (dosis total 43 mg), IV infusion de 1 hora, dias 1, 2 y 3\n- Mesna: 500 mg/m2 (dosis total 875 mg), IV antes, a las 4 y a las 8 horas de la administracion de ifosfamida (uroprotector)\n- Pegfilgrastim: 6 mg SC, dia +4 (soporte, no citotoxico)',
    premedicacion: '- SSN 0.9%: 1000 cc (antes de quimioterapia)\n- Fosaprepitant: 150 mg IV (dia 1)\n- Ondansetron: 16 mg IV (dia 1 al 3)\n- Dexametasona: 8 mg IV (dia 1 al 3)\n- Difenhidramina: 50 mg IV (antes de paclitaxel)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '4 ciclos, cada 21 dias',
  },
  {
    nombre: 'Esquema VIP (Cisplatino + Etoposido + Ifosfamida) para tumor mediastinal no seminomatoso; incluye ademas nota de Trabectedina',
    patologia: 'Tumor mediastinal no seminomatoso (tumor de celulas germinales) en paciente masculino; nota adicional menciona sarcoma de ovario para dosis alternativa de Trabectedina',
    medicamentos: '- Cisplatino: 20 mg/m2 IV dias 1 a 5 (aplicar 32 mg en 250 cc SSN, 1 hora)\n- Etoposido: 75 mg/m2 IV dias 1 a 5 (aplicar 120 mg en 500 cc SSN, 1 hora)\n- Ifosfamida: 1200 mg/m2 IV dias 1 a 5 (diluir 1900 mg en 250 cc DAD, pasar en 3 horas)\n- Trabectedina: 1.5 mg/m2 (dosis total 2.5 mg) IV en infusion continua de 24 horas, dia 1 cada 3 semanas; en sarcoma de ovario dosis de 0.58 mg/m2 en infusion de 3 horas dias 1, 8 y 15',
    premedicacion: '- Dexametasona: 16 mg (2 amp de 8 mg) IV (30 minutos antes de la quimioterapia, dias 1 a 5)\n- Ondansetron: 16 mg (2 amp de 8 mg) IV (30 minutos antes de cada quimioterapia, dias 1 a 5)\n- Mesna: 380 mg (a las horas 0, 4 y 8 de la dosis de ifosfamida, dias 1 a 5)\n- Fosaprepitant: 150 mg IV (antes de iniciar la quimioterapia)\n- Ondansetron tab 8 mg (ambulatorio VIP): 1 tableta VO (cada 8 horas si nauseas y/o vomito)\n- Dexametasona (premedicacion docetaxel/trabectedina): 16 mg IV (No especificado)\n- Difenhidramina (premedicacion docetaxel/trabectedina): 50 mg IV (No especificado)\n- Ondansetron (premedicacion docetaxel/trabectedina): 16 mg IV (No especificado)\n- Ondansetron tab 8 mg (ambulatorio trabectedina): 1 tab VO (cada 12 horas, No 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Esquema VIP: 4 ciclos cada 21 dias (1er de 4 ciclos formulado); Trabectedina: cada 3 semanas (numero total no especificado)',
  },
  {
    nombre: 'FLO (Oxaliplatino, Acido folinico, 5-Fluorouracilo)',
    patologia: 'Cancer gastrico (estudio de sobreexpresion de HER2 e inestabilidad microsatelital en muestra de patologia, CA 19-9, esquema FLO tipico de cancer gastrico/union gastroesofagica)',
    medicamentos: '- Oxaliplatino: 85 mg/m2 (dosis total 135 mg) IV, dias 1 y 15\n- Acido folinico: 200 mg/m2 (dosis total 636 mg) IV, dias 1 y 15\n- 5-Fluorouracilo: 2600 mg/m2 (dosis total 4134 mg) infusion continua 24 horas, dias 1 y 15',
    premedicacion: '- Dexametasona: 16 mg IV (dia)\n- Ondansetron: 16 mg IV (dia)\n- Albendazol: 400 mg, 1 tab VO (dia por 3 dias)\n- Metronidazol: 500 mg, 1 tab VO (cada 8 h por 5 dias)\n- Loperamida: 2 mg tab VO (cada 8 horas en caso de diarrea, No 20)\n- Ondansetron (adicional): 8 mg tab VO (cada 8 horas por 5 dias, No 20)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'Ciclos cada 28 dias hasta toxicidad o progresion',
  },
  {
    nombre: 'FLOT',
    patologia: 'Cáncer gástrico / de la unión gastroesofágica (esquema perioperatorio FLOT)',
    medicamentos: '- Docetaxel: 50 mg/m2 (Dosis total 75 mg IV en infusión de 1 hora, día 1 y 15)\n- Oxaliplatino: 85 mg/m2 (Dosis total 127 mg IV en infusión de 2 horas, día 1 y 15)\n- Folinato de calcio: 200 mg/m2 (Dosis total 600 mg IV en infusión de 30 minutos, día 1 y 15)\n- 5-Fluorouracilo: 2600 mg/m2 (Dosis total 3900 mg, infusión de 24 h, día 1 y 15)',
    premedicacion: '- Fosaprepitant: 150 mg IV (día (previo a quimio); repetido en segunda sección del documento)\n- Dexametasona: 8 mg IV (día); también 16 mg IV en otra sección del documento (día)\n- Ondansetron: 16 mg IV (día)\n- Clemastina: 2 mg IV (No especificado)\n- Ondansetron (ambulatorio): 8 mg VO (cada 12 horas por 20 días, No 40; en otra parte: cada 12 h por 5 días, No 20)\n- Albendazol: 200 mg, 2 tab VO (por día durante 5 días, No 10)\n- Metronidazol: 500 mg, 1 tab VO (cada 8 h por 3 días, No 10)\n- Loratadina: 10 mg, 1 tab VO (noche, iniciar 2 días antes de aplicación de ciclo, por 4 días, No 8)\n- Difenhidramina: 50 mg tab VO (1 tab el día de quimioterapia)',
    frecuencia_aplicacion: 'Cada 2 semanas',
    cantidad_ciclos: '8 ciclos (Cuatro ciclos preoperatorios seguidos de cuatro ciclos post operatorios; cada ciclo de 2 semanas)',
  },
  {
    nombre: 'FOLFIRI',
    patologia: 'Cancer colorrectal (se solicita CEA de control, marcador tumoral colorrectal)',
    medicamentos: '- Irinotecan: 180 mg/m2 (dosis total 360 mg) IV infusion 1 hora, dia 1 y 15\n- Acido folinico: 400 mg/m2 (dosis total 800 mg) IV en bolo de 2 horas, dia 1 y 15\n- 5-Fluorouracilo (bolo): 400 mg/m2 (dosis total 800 mg) IV infusion 2 horas, dia 1 y 15\n- 5-Fluorouracilo (infusion continua): 2400 mg/m2 (dosis total 4800 mg) IV infusion 46 horas, dia 1 y 15',
    premedicacion: '- Atropina: 0.5 mg SC (30 min antes de aplicacion de irinotecan)\n- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1)\n- Loperamida: 2 mg (1 tab VO) (cada 6 horas en caso de diarrea)\n- Ondansetron (VO ambulatorio): 8 mg (1 tab VO) (cada 12 horas)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'Ciclos cada 28 dias (cantidad total no especificada)',
  },
  {
    nombre: 'FOLFIRI + Bevacizumab',
    patologia: 'Cancer colorrectal (se solicita CEA de control, marcador tumoral colorrectal)',
    medicamentos: '- Bevacizumab: 5 mg/kg IV infusion 30 min, dia 1 y 15\n- Irinotecan: 180 mg/m2 (dosis total 306 mg) IV infusion 1 hora, dia 1 y 15\n- Acido folinico: 400 mg/m2 (dosis total 680 mg) IV en bolo de 2 horas, dia 1 y 15\n- 5-Fluorouracilo (bolo): 400 mg/m2 (dosis total 680 mg) IV infusion 2 horas, dia 1 y 15\n- 5-Fluorouracilo (infusion continua): 2400 mg/m2 (dosis total 4000 mg) IV infusion 46 horas, dia 1 y 15',
    premedicacion: '- Atropina: 0.5 mg SC (30 min antes de aplicacion de irinotecan)\n- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1)\n- Loperamida: 2 mg (1 tab VO) (cada 6 horas en caso de diarrea)\n- Ondansetron (VO ambulatorio): 8 mg (1 tab VO) (cada 12 horas)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'Ciclos cada 28 dias (cantidad total no especificada)',
  },
  {
    nombre: 'FOLFIRI + Panitumumab',
    patologia: 'Cancer colorrectal metastasico (esquema FOLFIRI + anti-EGFR panitumumab)',
    medicamentos: '- Panitumumab: 6 mg/kg IV infusion 1 hora, dias 1 y 15\n- Irinotecan: 180 mg/m2 IV infusion 1 hora, dia 1 y 15\n- Acido folinico: 400 mg/m2 IV bolo de 2 horas, dia 1 y 15\n- 5-Fluorouracilo: 400 mg/m2 IV infusion 2 horas, dia 1 y 15\n- 5-Fluorouracilo: 2400 mg/m2 IV infusion de 46 horas, dia 1 y 15',
    premedicacion: '- Fosaprepitant: 150 mg IV (dia 1 y 5)\n- Atropina: 0.5 mg SCT (30 min antes de irinotecan)\n- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'No especificado (ciclos cada 28 dias)',
  },
  {
    nombre: 'FOLFOX 6m y FOLFOX + Bevacizumab',
    patologia: 'Cancer colorrectal metastasico (esquema FOLFOX y FOLFOX + Bevacizumab, estandar en cancer colorrectal); marcadores solicitados ACE y CA 19-9 consistentes con seguimiento colorrectal/gastrointestinal',
    medicamentos: '- Oxaliplatino (FOLFOX 6m): 85 mg/m2 (dosis total 147 mg), infusion de 3 horas, dia 1 y 15\n- Acido folinico (FOLFOX 6m): 400 mg/m2 (dosis total 692 mg), IV en bolo de 2 horas, dia 1 y 15\n- 5-Fluorouracilo bolo (FOLFOX 6m): 400 mg/m2 (dosis total 692 mg), IV infusion de 2 horas, dia 1 y 15\n- 5-Fluorouracilo infusion continua (FOLFOX 6m): 2400 mg/m2 (dosis total 4152 mg), IV infusion de 46 horas, dia 1 y 15\n- Oxaliplatino (FOLFOX + Bevacizumab): 85 mg/m2 (dosis total 137 mg), infusion de 3 horas, dia 1 y 15\n- Acido folinico (FOLFOX + Bevacizumab): 400 mg/m2 (dosis total 648 mg), IV en bolo de 2 horas, dia 1 y 15\n- 5-Fluorouracilo bolo (FOLFOX + Bevacizumab): 400 mg/m2 (dosis total 648 mg), IV infusion de 2 horas, dia 1 y 15\n- 5-Fluorouracilo infusion continua (FOLFOX + Bevacizumab): 2400 mg/m2 (dosis total 3888 mg), IV infusion de 46 horas, dia 1 y 15\n- Bevacizumab: 7.5 mg/kg (dosis total 487 mg), IV infusion de 90 min, dia 1 y 15',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1 y 15)\n- Dexametasona: 16 mg IV (dia 1 y 15)\n- Ondansetron (ambulatorio): 8 mg VO tab (cada 8 horas por 5 dias, No. 20)\n- Loperamida (ambulatorio, en caso de diarrea): 2 mg VO tab (cada 6 horas en caso de diarrea, No. 20)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'Ciclos cada 28 dias; FOLFOX 6m: 1 ciclo formulado (total no especificado); FOLFOX + Bevacizumab: No especificado el numero total',
  },
  {
    nombre: 'Gemcitabina + Capecitabina',
    patologia: 'No especificado explicitamente en el documento (esquema compatible con cancer de pancreas); se solicita CA 19-9 de control',
    medicamentos: '- Gemcitabina: 1000 mg/m2 (dosis total 1890 mg) IV en infusion de 1 hora, dias 1, 8 y 15\n- Capecitabina: 825 mg/m2 VO cada 12 horas (dosis total 3000 mg dia, 3 tab AM y 3 tab PM de 500 mg), dias 1 al 21',
    premedicacion: '- Ondansetron: 16 mg IV (previo a gemcitabina)\n- Dexametasona: No especificado (mg no indicado en el documento) (previo a gemcitabina)\n- Loperamida tab 2 mg: 1 tab VO (cada 6 horas en caso de diarrea, No 20)\n- Ondansetron tab 8 mg (ambulatorio): 1 tab VO (cada 12 horas, No 20)',
    frecuencia_aplicacion: 'Cada 4 semanas',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 4 semanas por 6 ciclos',
  },
  {
    nombre: 'Gemcitabina + Oxaliplatino (GEMOX)',
    patologia: 'No especificado explicitamente en el documento (esquema GEMOX habitualmente usado en colangiocarcinoma/via biliar o cancer de pancreas); se solicita CA 19-9 de control, compatible con neoplasia biliopancreatica',
    medicamentos: '- Gemcitabina: 1250 mg/m2 (dosis total 1812 mg) IV en infusion de 1 hora, dias 1 y 8\n- Oxaliplatino: 130 mg/m2 (dosis total 188 mg) IV en infusion de 3 horas, dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1 y dia 8)\n- Dexametasona: 16 mg IV (dia 1 y dia 8)\n- Ondansetron tab 8 mg (ambulatorio): 1 tab VO (cada 8 horas)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 28 dias (No especificado el numero total de ciclos del esquema)',
  },
  {
    nombre: 'Gemcitabine + Nab-paclitaxel',
    patologia: 'Cáncer de páncreas (seguimiento con CA 19-9)',
    medicamentos: '- Gemcitabine: 1000 mg/m2 (dosis total 1610 mg o 1480 mg según paciente) IV días 1, 8 y 15 (infusión de 1 hora)\n- Nab-paclitaxel: 125 mg/m2 (dosis total 203 mg o 185 mg según paciente) IV días 1, 8 y 15 (infusión de 30 min)',
    premedicacion: '- Ondansetron: 16 mg IV (día)\n- Dexametasona: 16 mg IV (día)\n- Clemastina: 2 mg IV (día)\n- Difenhidramina: 50 mg IV (día)\n- Acetaminofén: 1 gr VO (día)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'Ciclos cada 28 días (número total no especificado)',
  },
  {
    nombre: 'Irinotecan + Bevacizumab',
    patologia: 'No especificado explicitamente en el documento (esquema compatible con cancer colorrectal metastasico)',
    medicamentos: '- Irinotecan: 125 mg/m2 (dosis total 230 mg) IV en infusion de 90 minutos, dias 1 y 15\n- Bevacizumab: 7.5 mg/kg (dosis total 560 mg) IV en infusion, dias 1 y 15',
    premedicacion: '- Atropina: 0.5 mg SC (30 minutos antes de aplicacion de irinotecan, dias 1 y 15)\n- Ondansetron: 16 mg IV (dias 1 y 15)\n- Dexametasona: 16 mg IV (dias 1 y 15)\n- Loperamida tab 2 mg: 1 tab VO (cada 6 horas en caso de diarrea, No 20)\n- Ondansetron tab 8 mg (ambulatorio): 1 tab VO (cada 12 horas, No 20)\n- Prednisolona tab 5 mg: 3 tab VO (dia, No 90)\n- Bisacodilo tab 5 mg: 1 tab VO (dia, No 30)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'Ciclos cada 28 dias (No especificado el numero total de ciclos del esquema)',
  },
  {
    nombre: 'Irinotecan + Temozolomida',
    patologia: 'No especificado (esquema Irinotecan+Temozolomida, tipicamente usado en sarcoma de Ewing recidivante/refractario u otros sarcomas; documento no consigna diagnostico explicito)',
    medicamentos: '- Temozolomida: 80 mg/m2 VO (dosis reducida por concurrencia con radioterapia), dias 1 al 5\n- Irinotecan: 100 mg/m2 IV infusion 1 hora, dias 1 al 15',
    premedicacion: '- Atropina: 0.5 mg SCT (30 min antes de irinotecan)\n- Ondansetron: 16 mg IV (dia 1 y 15)\n- Dexametasona: 8 mg IV (dia 1 y 15)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'No especificado (ciclos cada 21 dias)',
  },
  {
    nombre: 'MAI (Mesna, Doxorubicina, Ifosfamida)',
    patologia: 'Sarcoma (esquema MAI, indicado tipicamente en sarcoma de tejidos blandos/oseo)',
    medicamentos: '- Ifosfamida: 1800 mg/m2 dias 1 a 3 (2800 mg IV)\n- Mesna: 80% de dosis de ifosfamida (dosis total 2240 mg, 746 mg IV en infusion de 15 min a las 0, 4 y 8 horas de la ifosfamida)\n- Doxorubicina: 25 mg/m2/dia (39 mg), dias 1 y 2',
    premedicacion: '- Ondansetron: 16 mg IV (dia)\n- Dexametasona: 16 mg IV (dia)\n- Pegfilgrastim: 6 mg SCT (dia 3)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '6 ciclos, cada 21 dias',
  },
  {
    nombre: 'mFOLFIRINOX',
    patologia: 'No especificado en el documento (mFOLFIRINOX es el esquema estándar de cáncer de páncreas avanzado/metastásico)',
    medicamentos: '- Oxaliplatino: 85 mg/m2 IV, infusión de 2 horas, día 1 y 15\n- Irinotecan: 165 mg/m2 IV, infusión de 90 minutos, día 1 y 15 (según tolerancia, dosis a 180 mg)\n- Ácido folínico: 400 mg/m2 IV, infusión de 30 minutos, día 1 y 15\n- 5-Fluorouracilo: 2400 mg/m2 IV, infusión de 48 horas, día 1 y 15\n- Pegfilgrastim: 6 mg SCT, día +3 y +18',
    premedicacion: '- Fosaprepitant: 150 mg IV (No especificado)\n- Dexametasona: 16 mg IV (No especificado)\n- Ondansetron: 16 mg IV (No especificado)\n- Loperamida: tab 2 mg, 1 tab VO (cada 6 horas en caso de diarrea, No 20)\n- Ondansetron (ambulatorio): tab 8 mg, 1 tab VO (cada 12 horas, No 20)\n- Lorazepam: 1 mg, 1 tab VO (noche, No 30)\n- Albendazol: tab 200 mg, 2 tab VO (por 5 días)\n- Metronidazol: tab 500 mg, 1 tab VO (cada 8 horas por 3 días)',
    frecuencia_aplicacion: 'Cada 2 semanas',
    cantidad_ciclos: 'No especificado (ciclo día 1 y 15; se indica control cada 2 semanas posterior a inicio de ciclo)',
  },
  {
    nombre: 'No especificado (Esquema Dactinomicina)',
    patologia: 'No especificado (esquema de Dactinomicina con seguimiento de BHCG cuantitativa, compatible con enfermedad trofoblástica gestacional/tumor de células germinales; diagnóstico no explícito en el documento)',
    medicamentos: '- Dactinomicina: 1.25 mg/m2, IV en bolo de 15 min, Día 1 y 15',
    premedicacion: '- Ondansetron: 16 mg IV (día 1)\n- Dexametasona: 8 mg IV (día (no especifica día exacto))',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'No especificado (se formula 1 ciclo, ciclos cada 28 días)',
  },
  {
    nombre: 'No especificado (Esquema Doxorrubicina - Etopósido - Cisplatino)',
    patologia: 'No especificado (esquema compatible con tumor de células germinales/carcinoma de origen desconocido tipo DEC; diagnóstico no explícito en el documento)',
    medicamentos: '- Doxorrubicina: 50 mg/m2 (Dosis Total 95 mg IV en 30 minutos, Día 1)\n- Etopósido: 100 mg/m2 (Dosis Total 190 mg IV en 3 horas, Días 2, 3 y 4)\n- Cisplatino: 40 mg/m2 (Dosis Total 76 mg IV en infusión de 1 hora, Días 3 y 4)\n- Pegfilgrastim: 6 mg SC, Día +5 (soporte, no citotóxico)',
    premedicacion: '- SSN 0.9%: 1000 cc IV (antes y después de cisplatino)\n- Fosaprepitant: 150 mg IV (día 1)\n- Ondansetron: 16 mg IV (día (no especifica día exacto))\n- Dexametasona: No especificado (mg IV) (día (no especifica día exacto))\n- Furosemida: 20 mg IV (posterior a cisplatino)\n- Ondansetron (ambulatorio): 8 mg VO (1 tab cada 8 horas, No 20)\n- Prednisolona: 5 mg tab (1.5 tab = 7.5 mg) VO (día 6, 00 AM)',
    frecuencia_aplicacion: 'Cada 28 días',
    cantidad_ciclos: 'No especificado (se formula 1 ciclo, ciclos cada 28 días)',
  },
  {
    nombre: 'Paclitaxel (esquema quincenal; documento tambien lista esquemas alternativos de referencia: 60 mg/m2 semanal, 100 mg/m2 cada 15 dias, 135 mg/m2 cada 21 dias)',
    patologia: 'No especificado (documento no consigna diagnostico explicito; incluye estudios de EVDA y colonoscopia que sugieren posible origen gastrointestinal, sin confirmacion textual)',
    medicamentos: '- Paclitaxel: 100 mg/m2 IV infusion 1 hora, dias 1 y 15',
    premedicacion: '- Ondansetron: 16 mg IV (No especificado)\n- Dexametasona: 4 mg IV (No especificado)\n- Clemastina: 2 mg IV (No especificado)\n- Loratadina: 10 mg VO (1 tab noche, iniciar 2 dias antes de aplicacion)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'No especificado (ciclos cada 21 dias hasta progresion o toxicidad)',
  },
  {
    nombre: 'Paclitaxel + Carboplatino',
    patologia: 'Cáncer de ovario (seguimiento con CA 125)',
    medicamentos: '- Paclitaxel: 175 mg/m2 (dosis total 276 mg) IV Día 1 (infusión de 3 horas)\n- Carboplatino: AUC 5 (dosis total 625 mg) IV Día 1 (infusión de 1 hora)',
    premedicacion: '- Pegfilgrastim: 6 mg SCT (día +2)\n- Ondansetron: 16 mg IV (No especificado)\n- Dexametasona: 8 mg IV (No especificado)\n- Clemastina: 2 mg IV (No especificado)\n- Prednisolona: 5 mg (2 tab cada 12 h) (por 2 días, iniciar un día antes del paclitaxel, No. 16)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 días por 6 ciclos',
  },
  {
    nombre: 'PACLITAXEL semanal + TRASTUZUMAB cada 21 días',
    patologia: 'Cáncer de mama HER2 positivo',
    medicamentos: '- Paclitaxel: 80 mg/m2 (dosis total no especificada) IV, día 1, 8, 15 y 22\n- Trastuzumab: 492 mg (6 mg/kg) IV, día 1',
    premedicacion: '- Ondansetron: 16 mg IV (día 1, 8, 15 y 22)\n- Dexametasona: 16 mg IV (día 1, 8, 15 y 22)\n- Clemastina: 2 mg IV (día 1, 8, 15 y 22)\n- Difenhidramina: 50 mg tab VO (1 tab antes de la quimio)\n- Ondansetron (ambulatorio): 8 mg VO (1 tab cada 12 horas, No 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'No especificado (protocolo administrado cada 21 días, con paclitaxel semanal días 1, 8, 15 y 22)',
  },
  {
    nombre: 'Pembrolizumab + Axitinib',
    patologia: 'Carcinoma renal de celulas claras metastasico (esquema estandar pembrolizumab + axitinib en primera linea de carcinoma renal avanzado)',
    medicamentos: '- Pembrolizumab: dosis total 200 mg, IV infusion de 30 minutos, dia 1\n- Axitinib: 5 mg VO, tomar 1 tab cada 12 h, No. 180 (formula por tres meses)',
    premedicacion: '- Difenhidramina: 50 mg VO tab, No. 1 (el dia de quimioterapia)\n- Ondansetron (ambulatorio): 8 mg VO tab (cada 12 horas, No. 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo, ciclos cada 21 dias (No especificado el numero total)',
  },
  {
    nombre: 'Pembrolizumab + Lenvatinib',
    patologia: 'No especificado (esquema estandar pembrolizumab+lenvatinib usado en carcinoma de endometrio/CHC; se solicita CA 125 de control)',
    medicamentos: '- Pembrolizumab: 200 mg IV infusion de 30 minutos, dia 1\n- Lenvatinib: 20 mg VO/dia (2 tab de 10 mg)',
    premedicacion: '- Clemastina: 2 mg IV (No especificado)\n- Ondansetron (VO ambulatorio): 8 mg (1 tab VO) (cada 12 horas)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 21 dias (cantidad total no especificada)',
  },
  {
    nombre: 'Quimiorradiación concurrente con Cisplatino (documento incluye múltiples esquemas: 1 ciclo días 1,21,42; semanal x6; semanal x7)',
    patologia: 'No especificado en el documento (esquema de Cisplatino en quimiorradiación concurrente, uso típico en cáncer de cérvix o cabeza y cuello)',
    medicamentos: '- Cisplatino: 100 mg/m2 (Dosis Total 176 mg IV, infusión de 3 horas, día 1) - esquema cada 21 días\n- Cisplatino: 40 mg/m2 (Dosis total 48 mg IV, infusión de 3 horas, días 1, 8 y 15) - esquema semanal x6\n- Cisplatino: 40 mg/m2 (Dosis total 64 mg IV, infusión de 3 horas, días 1, 8 y 15) - esquema semanal x7',
    premedicacion: '- Hidratación SSN 0.9%: 1000 cc (antes y después de cisplatino)\n- Ondansetron: 16 mg IV (días de aplicación)\n- Fosaprepitant: 150 mg IV (días de aplicación)\n- Dexametasona: 16 mg IV (días de aplicación)\n- Furosemida: 20 mg IV (o 40 mg IV según esquema) (día después de terminar SSN 0.9%)\n- Ondansetron (ambulatorio): tab 8 mg, 1 tab VO (cada 12 horas x 20)\n- Albendazol: tab 400 mg, 1 tab VO (por 5 días)\n- Metronidazol: tab 500 mg, 1 tab VO (cada 8 horas por 3 días)',
    frecuencia_aplicacion: 'Semanal',
    cantidad_ciclos: '1 ciclo (días 1, 21 y 42) / semanal por 6 aplicaciones / semanal por 7 aplicaciones (esquemas múltiples en el mismo documento)',
  },
  {
    nombre: 'Quimiorradiación concurrente con Cisplatino semanal (IDX: CA)',
    patologia: 'No especificado en el documento (esquema de Cisplatino semanal concurrente con radioterapia, uso típico en cáncer de cérvix u otros tumores de cabeza/cuello o pélvicos tratados con quimiorradiación)',
    medicamentos: '- Cisplatino: 40 mg/m2 (Dosis Total 63 mg IV, infusión de 3 horas)',
    premedicacion: '- Ondansetron: 16 mg IV (semanal por 6 semanas)\n- Fosaprepitant: 150 mg IV (semanal por 6 semanas)\n- Dexametasona: 16 mg IV (semanal por 6 semanas)\n- Furosemida: 40 mg IV (día después de terminar SSN 0.9%, semanal por 6 semanas)\n- Hidratación SSN 0.9%: 1000 cc (antes y después de cisplatino)\n- Ondansetron (ambulatorio): tab 8 mg, 1 tab VO (cada 12 horas x 20)',
    frecuencia_aplicacion: 'Semanal',
    cantidad_ciclos: '6 semanas (semanal, concurrente con radioterapia)',
  },
  {
    nombre: 'RAMUCIRUMAB PACLITAXEL',
    patologia: 'No especificado',
    medicamentos: '- Paclitaxel: 80 mg/m2 semanal, dias 1, 8 y 15 del ciclo\n- Ramucirumab: 8 mg/kg, dias 1 y 15 del ciclo',
    premedicacion: '- Dexametasona: 16 mg IV (antes de la quimioterapia, dias 1, 8 y 15 del ciclo)\n- Ondansetron: 16 mg IV (antes de la quimioterapia, dias 1, 8 y 15 del ciclo)\n- Loratadina: 10 mg, 2 tabletas (1 hora antes de la quimioterapia, dias 1, 8 y 15 del ciclo)\n- Ondansetron (medicacion asociada): 8 mg tableta (1 tableta cada 12 horas si presenta nauseas y/o vomito)\n- Pegfilgrastim: 6 mg subcutaneo, dosis unica (dia 2 del ciclo)',
    frecuencia_aplicacion: 'No especificado',
    cantidad_ciclos: 'No especificado',
  },
  {
    nombre: 'TIP',
    patologia: 'No especificado (esquema TIP: Paclitaxel-Ifosfamida-Cisplatino, usado en tumores de células germinales/cáncer cervical recurrente; diagnóstico no explícito en el documento)',
    medicamentos: '- Paclitaxel: 175 mg/m2 (Dosis total 311 mg) IV en infusión de 3 horas, Día 1\n- Ifosfamida: 1200 mg/m2 (Dosis total 2136 mg) IV en infusión de 2 horas, días 1, 2 y 3\n- Cisplatino: 25 mg/m2 (Dosis total 45 mg) IV en infusión de 1 hora, día 1, 2 y 3\n- Mesna: 500 mg/m2 (Dosis total 900 mg) IV antes, a las 4 y a las 8 horas de la administración de ifosfamida (uroprotector)\n- Pegfilgrastim: 6 mg SC, día +4 (soporte, no citotóxico)',
    premedicacion: '- SSN 0.9%: 1000 cc IV (antes de quimioterapia)\n- Fosaprepitant: 150 mg IV (día 1)\n- Ondansetron: 16 mg IV (día 1 al 3)\n- Dexametasona: 8 mg IV (día 1 al 3)\n- Difenhidramina: 50 mg IV (antes de paclitaxel)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '4 ciclos (cada 21 días)',
  },
  {
    nombre: 'TIP (Paclitaxel + Ifosfamida + Cisplatino)',
    patologia: 'Tumor germinal testicular (esquema TIP, tipicamente usado en enfermedad recurrente/refractaria)',
    medicamentos: '- Paclitaxel: 175 mg/m2 (dosis total 374 mg) IV infusion continua de 24 horas, dia 1\n- Ifosfamida: 1500 mg/m2 (dosis total 3210 mg) IV infusion 1 hora, dias 2, 3, 4 y 5\n- Cisplatino: 25 mg/m2 (dosis total 96 mg) IV infusion 1 hora, dias 2, 3, 4 y 5\n- Mesna: 500 mg/m2 (dosis total 1070 mg) IV antes, a las 4 y a las 8 horas de administracion de ifosfamida, dias 2,3,4,5',
    premedicacion: '- SSN 0.9%: 1000 cc (antes de quimioterapia)\n- Manitol 10%: 50 cc previo a cisplatino, continuar 30 cc/hora durante infusion (premedicacion de cisplatino)\n- Ondansetron: 16 mg IV (dia 1 al 5)\n- Dexametasona: 24 mg IV (dia 1 al 5)\n- Pegfilgrastim: 6 mg SC (dia +6)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '4 a 6 ciclos, ciclos cada 21 dias',
  },
  {
    nombre: 'Trabectedina',
    patologia: 'No especificado en el documento (Trabectedina está indicada principalmente en sarcoma de tejidos blandos avanzado)',
    medicamentos: '- Trabectedina: 1 mg (0.58 mg/m2) IV, infusión de 3 horas, días 1, 8 y 15',
    premedicacion: '- Dexametasona: 16 mg IV (No especificado)\n- Difenhidramina: tab 50 mg, 1 tab VO (el día de quimioterapia)\n- Ondansetron: 16 mg IV (No especificado)\n- Ondansetron (ambulatorio): tab 8 mg, 1 tab VO (cada 12 horas x 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 días',
  },
  {
    nombre: 'Trabectedina monoterapia, con variante de esquema TIP (Paclitaxel + Ifosfamida + Cisplatino) para sarcoma de ovario',
    patologia: 'Sarcoma de tejidos blandos (trabectedina es esquema estandar de sarcoma de tejidos blandos avanzado/metastasico); el documento menciona explicitamente sarcoma de ovario como indicacion de la variante de dosis',
    medicamentos: '- Trabectedina: 1.5 mg/m2 (dosis total 2.5 mg), IV infusion continua de 24 horas, dia 1, cada 3 semanas (nota: en sarcoma de ovario la dosis es 0.58 mg/m2 en infusion de 3 horas, dias 1, 8 y 15)\n- Paclitaxel (esquema TIP): 175 mg/m2 (dosis total 306 mg), IV infusion de 3 horas, dia 1\n- Ifosfamida (esquema TIP): 1200 mg/m2 (dosis total 2100 mg), IV infusion de 2 horas, dias 1, 2 y 3\n- Cisplatino (esquema TIP): 25 mg/m2 (dosis total 43 mg), IV infusion de 1 hora, dia 1, 2 y 3\n- Mesna (esquema TIP): 500 mg/m2 (dosis total 875 mg), IV antes, a las 4 y a las 8 horas de la administracion de ifosfamida (uroprotector)\n- Pegfilgrastim (esquema TIP): 6 mg SC, dia +4 (soporte, no citotoxico)',
    premedicacion: '- Dexametasona: 16 mg IV (premedicacion de trabectedina/docetaxel)\n- Difenhidramina: 50 mg IV (premedicacion (antes de paclitaxel en esquema TIP))\n- Ondansetron: 16 mg IV (premedicacion)\n- Ondansetron (ambulatorio): 8 mg VO tab (cada 12 horas, No. 20)\n- Albendazol: 200 mg, 2 tab VO (al dia por 5 dias, No. 10)\n- Metronidazol: 500 mg, 1 tab VO (cada 8 h por 3 dias, No. 10)\n- Acetaminofen: 500 mg tab, No. 60 (2 tab VO cada 8 horas)\n- SSN 0.9% (esquema TIP): 1000 cc (antes de quimioterapia)\n- Fosaprepitant (esquema TIP): 150 mg IV (dia 1)\n- Ondansetron (esquema TIP): 16 mg IV (dia 1 al 3)\n- Dexametasona (esquema TIP): 8 mg IV (dia 1 al 3)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Trabectedina: 1 ciclo cada 3 semanas (No especificado el numero total); esquema TIP: 4 ciclos cada 21 dias',
  },
  {
    nombre: 'Trastuzumab emtansine',
    patologia: 'Cáncer de mama HER2 positivo',
    medicamentos: '- Trastuzumab emtansine: 3.6 mg/kg (dosis total 180 mg) IV día 1 (infusión de 90 min)',
    premedicacion: '- Ondansetron: 16 mg IV (día 1)\n- Dexametasona: 16 mg IV (día 1)\n- Difenhidramina: 50 mg VO (día 1)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'Ciclos cada 21 días (número total no especificado)',
  },
  {
    nombre: 'VAC (Vincristina-Doxorrubicina-Ciclofosfamida) e IE (Ifosfamida-Etopósido) - documento combinado',
    patologia: 'Sarcoma de Ewing (esquema estándar VAC/IE)',
    medicamentos: '- Vincristina: 1 mg/m2 (máximo 2 mg), Dosis total 2 mg IV en bolo, Día 1\n- Doxorrubicina: 75 mg/m2, Dosis total 150 mg IV en infusión de 30 min, Día 1\n- Ciclofosfamida: 1200 mg/m2, Dosis Total 2400 mg IV en infusión de 3 horas, Día 1\n- Pegfilgrastim (esquema VAC): 6 mg SC, día +2 (soporte, no citotóxico)\n- Ifosfamida (esquema IE): 1800 mg/m2 (días 1 al 5), Dosis total 2700 mg IV en infusión de 2 horas, días 1 al 5\n- Etopósido (esquema IE): 100 mg/m2 (días 1 al 5), Dosis total 151 mg IV en infusión de 2 horas, días 1 al 5\n- Pegfilgrastim (esquema IE): 6 mg SC, día +6 (soporte, no citotóxico)',
    premedicacion: '- Mesna (esquema VAC): 800 mg IV (a las 0, 4 y 8 horas de la ciclofosfamida)\n- Fosaprepitant (esquema VAC): 150 mg IV (día 1)\n- Ondansetron (esquema VAC): 16 mg IV (No especificado)\n- Dexametasona (esquema VAC): 16 mg IV (No especificado)\n- Albendazol: 200 mg, 2 tab VO (por día, durante 5 días, No 10)\n- Metronidazol: 500 mg, 1 tab VO (cada 8 h por 3 días, No 10)\n- Ondansetron tab (ambulatorio): 8 mg VO (1 tab cada 12 horas, No 20)\n- Mesna (esquema IE): 60-80% de dosis de ifosfamida, Dosis total 800 mg IV en infusión de 15 minutos (a las 0, 4 y 8 horas de la ifosfamida)\n- Fosaprepitant (esquema IE): 150 mg IV (día 1)\n- Ondansetron (esquema IE): 16 mg IV (No especificado)\n- Dexametasona (esquema IE): 16 mg IV (No especificado)\n- Ondansetron tab (ambulatorio, esquema IE): 8 mg VO (1 tab cada 12 horas, No 20)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'VAC: 6 ciclos cada 21 días (posteriormente inicio de dactinomicina); IE: 1 ciclo, ciclos cada 21 días (cantidad total no especificada)',
  },
  {
    nombre: 'VeIP',
    patologia: 'Tumor de células germinales testicular (documento incluye envío urgente a banco de esperma y seguimiento de BHCG/AFP, marcadores tumorales característicos)',
    medicamentos: '- Vinblastina: 0.11 mg/kg (dosis total no especificada) IV en bolo, día 1 y 2\n- Ifosfamida: 1200 mg/m2 (dosis total no especificada) IV en infusión de 1 hora, días 1, 2, 3, 4 y 5\n- Cisplatino: 20 mg/m2 (dosis total no especificada) IV en infusión de 1 hora, día 1, 2, 3, 4 y 5\n- Mesna: 400 mg/m2 (dosis total no especificada) IV antes, a las 4 y a las 8 horas de la administración de ifosfamida (uroprotector)\n- Pegfilgrastim: 6 mg SC, día +6 (soporte, no citotóxico)',
    premedicacion: '- SSN 0.9%: 1000 cc IV (antes de quimioterapia)\n- Fosaprepitant: 150 mg IV (día 1)\n- Ondansetron: 16 mg IV (día 1 al 5)\n- Dexametasona: 8 mg IV (día 1 al 5)\n- Furosemida: 20 mg IV (antes de cisplatino)\n- Ondansetron tab (ambulatorio): 8 mg VO (1 tab cada 12 horas, No 20)\n- Albendazol: 400 mg, 1 tab VO (por día durante 5 días, No 5)\n- Metronidazol: 500 mg, 1 tab VO (cada 8 h por 3 días, No 10)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '4 ciclos (cada 21 días)',
  },
  {
    nombre: 'VeIP (Vinblastina + Ifosfamida + Cisplatino) - segunda linea tumor germinal testicular',
    patologia: 'Tumor germinal testicular (segunda linea)',
    medicamentos: '- Vinblastina: 0,11 mg/kg IV durante 5-10 minutos, dias 1-2\n- Ifosfamida: 1200 mg/m2 IV durante 3 horas, dias 1-5\n- Cisplatino: 20 mg/m2 IV durante 60 minutos, dias 1-5\n- Mesna: 240 mg/m2 IV durante 15 minutos antes de ifosfamida, hora 0, 4 y 8, dias 1-5',
    premedicacion: '- Ondansetron: 16 mg (dias 1 a 5, cada dia)\n- Dexametasona: 16 mg IV (dias 1 a 5, cada dia)\n- Furosemida: 20 mg IV (premedicacion de cisplatino)\n- Sulfato de magnesio: 3 cc en cada 500 cc de SS (No especificado)\n- Cloruro de potasio: 5 cc en cada 500 cc de SS (No especificado)\n- Pegfilgrastim: 6 mg SC (dia 6)',
    frecuencia_aplicacion: 'Cada 3 semanas',
    cantidad_ciclos: 'No especificado (repetir ciclo cada 3 semanas)',
  },
  {
    nombre: 'Vinorelbina + Carboplatino',
    patologia: 'No especificado (esquema Vinorelbina+Carboplatino, tipicamente usado en cancer de pulmon no celulas pequenas; documento no consigna diagnostico explicito)',
    medicamentos: '- Vinorelbina: 25 mg/m2 IV, dia 1 y 8\n- Carboplatino: AUC 5 IV infusion 90 min, dia 1',
    premedicacion: '- Fosaprepitant: 150 mg IV (dia 1)\n- Dexametasona: 8 mg IV (dia 1 y 8)\n- Ondansetron: 16 mg IV (dia 1 y 8)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: 'No especificado (revision corresponde al ciclo 4; ciclos cada 21 dias)',
  },
  {
    nombre: 'XELOX (Capecitabina + Oxaliplatino)',
    patologia: 'No especificado explicitamente en el documento (esquema XELOX habitualmente usado en cancer colorrectal); se solicita CEA de control, compatible con neoplasia colorrectal',
    medicamentos: '- Capecitabina: 1000 mg/m2 VO cada 12 horas, dias 1 a 14 (tomar 3 tab AM y 4 tab PM de 500 mg)\n- Oxaliplatino: 130 mg/m2 (dosis total 248 mg) IV en infusion de 2 horas, dia 1',
    premedicacion: '- Ondansetron: 16 mg IV (dia 1)\n- Dexametasona: 16 mg IV (dia 1)\n- Loperamida tab 2 mg: 1 tab VO (cada 6 horas en caso de diarrea, No 20)\n- Ondansetron tab 8 mg (ambulatorio): 1 tab VO (cada 12 horas, No 20)\n- Albendazol 200 mg: 2 tab VO (dia por 5 dias, No 10)\n- Metronidazol tab 500 mg: 1 tab VO (cada 8 horas por 3 dias, No 10)',
    frecuencia_aplicacion: 'Cada 21 días',
    cantidad_ciclos: '1 ciclo formulado, ciclos cada 21 dias por 6 ciclos',
  },
];
